/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Customer
 */
public class Awal extends javax.swing.JFrame {

    /**
     * Creates new form Awal
     */
    public Awal() {
        initComponents();
        this.setLocationRelativeTo(null);
       //setExtendedState(MAXIMIZED_BOTH);
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Jam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mdata = new javax.swing.JMenu();
        misiswa = new javax.swing.JMenuItem();
        mijenis = new javax.swing.JMenuItem();
        mitu = new javax.swing.JMenuItem();
        mtransaksi = new javax.swing.JMenu();
        mipembayaran = new javax.swing.JMenuItem();
        mlaporan = new javax.swing.JMenu();
        mikwitansi = new javax.swing.JMenuItem();
        milapkelas = new javax.swing.JMenuItem();
        milapbulan = new javax.swing.JMenuItem();
        mkeluar = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 83, 118));

        Jam.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Jam.setForeground(new java.awt.Color(102, 204, 255));
        Jam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Jam.setText("--:--:--");

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Pembayaran SPP ");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELAMAT DATANG");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO KEMENTERIAN AGAMA.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MIs - NURHIDAYAH");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NPSN: 60706520");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JL. KALIBARU BARAT IV, NO.3 RT 002/012 ");

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("JAKARTA UTARA");

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("KEL.KALIBARU KEC.CILINCING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addComponent(Jam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Jam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 310));

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(102, 204, 255));
        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        mdata.setForeground(new java.awt.Color(13, 83, 118));
        mdata.setText("DATA");
        mdata.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        misiswa.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        misiswa.setForeground(new java.awt.Color(13, 83, 118));
        misiswa.setText("DATA SISWA");
        misiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misiswaActionPerformed(evt);
            }
        });
        mdata.add(misiswa);

        mijenis.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        mijenis.setForeground(new java.awt.Color(13, 83, 118));
        mijenis.setText("DATA JENIS PEMBAYARAN");
        mijenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mijenisActionPerformed(evt);
            }
        });
        mdata.add(mijenis);

        mitu.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        mitu.setForeground(new java.awt.Color(13, 83, 118));
        mitu.setText("DATA TU");
        mitu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mituActionPerformed(evt);
            }
        });
        mdata.add(mitu);

        jMenuBar1.add(mdata);

        mtransaksi.setForeground(new java.awt.Color(13, 83, 118));
        mtransaksi.setText("TRANSAKSI");
        mtransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        mipembayaran.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        mipembayaran.setForeground(new java.awt.Color(13, 83, 118));
        mipembayaran.setText("PEMBAYARAN");
        mipembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipembayaranActionPerformed(evt);
            }
        });
        mtransaksi.add(mipembayaran);

        jMenuBar1.add(mtransaksi);

        mlaporan.setForeground(new java.awt.Color(13, 83, 118));
        mlaporan.setText("LAPORAN");
        mlaporan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        mikwitansi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        mikwitansi.setForeground(new java.awt.Color(13, 83, 118));
        mikwitansi.setText("Kwitansi");
        mikwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mikwitansiActionPerformed(evt);
            }
        });
        mlaporan.add(mikwitansi);

        milapkelas.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        milapkelas.setForeground(new java.awt.Color(13, 83, 118));
        milapkelas.setText("Lap Kelas");
        milapkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milapkelasActionPerformed(evt);
            }
        });
        mlaporan.add(milapkelas);

        milapbulan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        milapbulan.setForeground(new java.awt.Color(13, 83, 118));
        milapbulan.setText("Lap PerBulan");
        milapbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milapbulanActionPerformed(evt);
            }
        });
        mlaporan.add(milapbulan);

        jMenuBar1.add(mlaporan);

        mkeluar.setForeground(new java.awt.Color(13, 83, 118));
        mkeluar.setText("KELUAR");
        mkeluar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        mkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mkeluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mkeluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mituActionPerformed
        // TODO add your handling code here:
        tu frmT = new tu();       
         frmT.setVisible(true);
    }//GEN-LAST:event_mituActionPerformed

    private void misiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misiswaActionPerformed
        // TODO add your handling code here:
        siswa frmS = new siswa();       
         frmS.setVisible(true);
    }//GEN-LAST:event_misiswaActionPerformed

    private void mijenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mijenisActionPerformed
        // TODO add your handling code here:
        jenis_pembayaran frmJ = new jenis_pembayaran();       
         frmJ.setVisible(true);
    }//GEN-LAST:event_mijenisActionPerformed

    private void mkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mkeluarMouseClicked
        // TODO add your handling code here:
        dispose();
        Login frmL = new Login();       
         frmL.setVisible(true);
    }//GEN-LAST:event_mkeluarMouseClicked

    private void mipembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mipembayaranActionPerformed
        // TODO add your handling code here:
         pembayaran frmP = new pembayaran();       
         frmP.setVisible(true);
    }//GEN-LAST:event_mipembayaranActionPerformed

    private void milapbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milapbulanActionPerformed
        // TODO add your handling code here:
        laporan.lap_perbulan frmB = new laporan.lap_perbulan();       
         frmB.setVisible(true);
    }//GEN-LAST:event_milapbulanActionPerformed

    private void mikwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mikwitansiActionPerformed
        // TODO add your handling code here:
         laporan.lap_kwitansi frmK = new laporan.lap_kwitansi();       
         frmK.setVisible(true);
    }//GEN-LAST:event_mikwitansiActionPerformed

    private void milapkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milapkelasActionPerformed
        // TODO add your handling code here:
        laporan.lap_kelas frmKl = new laporan.lap_kelas();       
         frmKl.setVisible(true);
    }//GEN-LAST:event_milapkelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mdata;
    private javax.swing.JMenuItem mijenis;
    private javax.swing.JMenuItem mikwitansi;
    private javax.swing.JMenuItem milapbulan;
    private javax.swing.JMenuItem milapkelas;
    private javax.swing.JMenuItem mipembayaran;
    private javax.swing.JMenuItem misiswa;
    private javax.swing.JMenuItem mitu;
    private javax.swing.JMenu mkeluar;
    private javax.swing.JMenu mlaporan;
    private javax.swing.JMenu mtransaksi;
    // End of variables declaration//GEN-END:variables


public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "",nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";
                String waktu = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Jam.setText(waktu+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }}
